// Static registration data for UI-only registration flow

export const universityData = {
  name: "Sample University",
  city: "Sample City",
  state: "Sample State",
  logo: "/sample-university-logo.png",
};

export const teamData = {
  name: "Sample Team",
  logo: "/sample-team-logo.png",
};

export const playersData = [
  {
    role: "captain",
    game_id: "Captain123",
    server_id: "ServerA",
    name: "Alice Captain",
    ign: "AliceIGN",
    email: "alice@example.com",
    phone: "1234567890",
    gender: "Female",
    picture_url: "/captain-pic.png",
    student_id_url: "/captain-id.png",
  },
  {
    role: "player",
    game_id: "Player2",
    server_id: "ServerA",
    name: "Bob Player",
    ign: "BobIGN",
    email: "bob@example.com",
    phone: "1234567891",
    gender: "Male",
    picture_url: "/player2-pic.png",
    student_id_url: "/player2-id.png",
  },
  {
    role: "player",
    game_id: "Player3",
    server_id: "ServerA",
    name: "Charlie Player",
    ign: "CharlieIGN",
    email: "charlie@example.com",
    phone: "1234567892",
    gender: "Male",
    picture_url: "/player3-pic.png",
    student_id_url: "/player3-id.png",
  },
  {
    role: "player",
    game_id: "Player4",
    server_id: "ServerA",
    name: "Dana Player",
    ign: "DanaIGN",
    email: "dana@example.com",
    phone: "1234567893",
    gender: "Female",
    picture_url: "/player4-pic.png",
    student_id_url: "/player4-id.png",
  },
  {
    role: "player",
    game_id: "Player5",
    server_id: "ServerA",
    name: "Eli Player",
    ign: "EliIGN",
    email: "eli@example.com",
    phone: "1234567894",
    gender: "Male",
    picture_url: "/player5-pic.png",
    student_id_url: "/player5-id.png",
  },
  {
    role: "substitute",
    game_id: "Sub123",
    server_id: "ServerA",
    name: "Fay Substitute",
    ign: "FayIGN",
    email: "fay@example.com",
    phone: "1234567895",
    gender: "Female",
    picture_url: "/sub-pic.png",
    student_id_url: "/sub-id.png",
  },
  {
    role: "coach",
    game_id: "Coach123",
    server_id: "ServerA",
    name: "Grace Coach",
    ign: "GraceIGN",
    email: "grace@example.com",
    phone: "1234567896",
    gender: "Female",
    picture_url: "/coach-pic.png",
    student_id_url: "/coach-id.png",
  },
];

export const registrationData = {
  university: universityData,
  team: teamData,
  players: playersData,
};
