export const volunteerData = {
    referralCode: "BKRAHUL2023",
    teamsJoined: 8,
    diamondsEarned: 2400,
    }

export const referredTeams = [
    {
      id: 1,
      logo: "/placeholder.svg?height=40&width=40",
      name: "Phoenix Warriors",
      captainName: "FireLord55",
      captainGameId: "BK87654321",
      captainServerId: "Asia-IN-56",
      registrationDate: "2023-10-15",
      status: "approved",
    },
    {
      id: 2,
      logo: "/placeholder.svg?height=40&width=40",
      name: "Dragon Slayers",
      captainName: "DragonMaster",
      captainGameId: "BK11223344",
      captainServerId: "Asia-IN-42",
      registrationDate: "2023-10-18",
      status: "approved",
    },
    {
      id: 3,
      logo: "/placeholder.svg?height=40&width=40",
      name: "Shadow Ninjas",
      captainName: "SilentKiller",
      captainGameId: "BK99887766",
      captainServerId: "Asia-IN-56",
      registrationDate: "2023-10-20",
      status: "pending",
    },
    {
      id: 4,
      logo: "/placeholder.svg?height=40&width=40",
      name: "Royal Knights",
      captainName: "KingSlayer",
      captainGameId: "BK55443322",
      captainServerId: "Asia-IN-28",
      registrationDate: "2023-10-22",
      status: "approved",
    },
    {
      id: 5,
      logo: "/placeholder.svg?height=40&width=40",
      name: "Mystic Mages",
      captainName: "SpellCaster",
      captainGameId: "BK12344321",
      captainServerId: "Asia-IN-56",
      registrationDate: "2023-10-25",
      status: "rejected",
    },
    {
      id: 6,
      logo: "/placeholder.svg?height=40&width=40",
      name: "Crimson Assassins",
      captainName: "SilentBlade",
      captainGameId: "BK98761234",
      captainServerId: "Asia-IN-42",
      registrationDate: "2023-10-28",
      status: "approved",
    },
    {
      id: 7,
      logo: "/placeholder.svg?height=40&width=40",
      name: "Thunder Strikers",
      captainName: "StormBringer",
      captainGameId: "BK13579246",
      captainServerId: "Asia-IN-56",
      registrationDate: "2023-11-01",
      status: "pending",
    },
    {
      id: 8,
      logo: "/placeholder.svg?height=40&width=40",
      name: "Frost Giants",
      captainName: "IceKing",
      captainGameId: "BK24681357",
      captainServerId: "Asia-IN-28",
      registrationDate: "2023-11-05",
      status: "approved",
    },
  ]

export const REFERRALTOAST = {
    title: "Referral Code Copied",
    description: "The referral code has been copied to your clipboard.",
  }