export type NorthEastCupItem = {
    id: number;
    image: string;
    title: string;
    description: string;
    stats: Record<string, string>;
    statColors: Record<string, string>;
    order_index: number; // Added for sorting purposes
  };
  
  
  export type MediaItem = {
    id: string;
    title: string;
    date: string;
    type: "image" | "video";
    image: string;
    aspectRatio?: "portrait" | "landscape" | "square"; // For better sizing control
    description?: string;
    order_index: number; // Added for sorting purposes
  };
  
  // types/homepageTypes.ts
export interface CosplayItem {
  id?: string; // Optional for new items (UUID generated by DB on insert), required for existing
  order_index: number; // For controlling the display order
  image: string; // The URL of the image
  created_at?: string; // <--- ADD THIS LINE (optional for new, present for existing)
}
  
  export type FeaturedItem = {
    title: string,
    date: string,
    location: string,
    description: string,
    teamCount:  number,
    prizePool: string,
    ticketsUrl: string,
    watchUrl: string,
    bannerImage: string,
  }